### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by akaAMAZING** [vlameiras/poe-trade-parser#1]
Hi, is there a way to search for more than one filter at a time?

Or would you simply suggest running multiple applications for each filter?

**Comment by vlameiras** [comment]
Hi,

As it is, I think that running multiple applications might be the way to
go. However, I have not tested if there are any limitations to the number
of parallel websocket connections. This was an issue for POE.trade, only
one websocket connection per IP at a given time.

Thanks
